### ISSUE TITLE
很多很多的bug

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [PCL-Community/PCL-GitView-Beta#1]
1.点击导航栏的任何一个按钮都会跳转到组织官网
2.点击“什么是PCL-GitView“按钮后提示403 forbidden
3.点击“快速开始”按钮后一直转圈
复现视频：
https://pan.huang1111.cn/s/zPMBfM

**Comment by Deep-Dark-Forest** [comment]
@JingHai-Lingyun

**Comment by MoYuan-CN** [comment]
403 Forbidden 是我还没写好，挂上去的
快速开始按钮点击后转圈我晚点看看，怀疑Key炸了

**Comment by MoYuan-CN** [comment]
不是 Key 炸了，是我的缓存 API 关掉了（

**Comment by MoYuan-CN** [comment]
> 1.点击导航栏的任何一个按钮都会跳转到组织官网

浏览器导致的

---

鉴于以上内容均已做出解释，下一个版本修复 "点击“快速开始”按钮后一直转圈" 的问题，先关了，开 #2
